### ISSUE TITLE
phylomatic not accepting higher taxon

### ISSUE THREAD

**Issue by christophebenjamin** [ropensci/brranching#44]
`brranching::phylomatic` does not accept a list of taxon other than species for the binindaemonds2007 stored tree. For example, if I input a list of genus of mammals, The error  No taxa in common is produced.

Would you know why?

Thank you,

Christophe

Code example

```r
taxa<-c("Canis", "Vulpes","Lycaon", "Nyctereutes", "Otocyon" )
phylomatic(taxa = taxa, get = "POST", storedtree = "binindaemonds2007", clean = T, db="ncbi")
```

**Comment by sckott** [comment]
thanks for opening the issue here. 

I think it's because binindaemonds2007 doesn't appear to have higher level taxon family or genus names in the tree, so if there's no exact name match to a name, e..g, Vulpes, then nothing is returned. 

If you have species names then it works, but maybe you can only use generic names?

**Comment by christophebenjamin** [comment]
Thanks for your response! 
It makes sense! Just to clarify by using generic names you mean choosing an arbitrary species within the genus I want to show in the tree?

**Comment by sckott** [comment]
yes
